name: pawlink
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  path_provider: ^2.1.1
  flutter_svg: ^2.0.6
  google_fonts: ^5.0.0
  feather_icons: ^1.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  get: ^4.6.1


flutter:
  uses-material-design: true

